spring:
  datasource:
    url: jdbc:h2:~/camunda-h2-database;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver

server:
  address: localhost
  port: 8801
  servlet:
    context-path: /camunda

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    client:
      base-url: http://localhost:8801/camunda/engine-rest